name: Send mail
on: push
jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      if: ${{ always() }} 
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.google.com
        # Optional port (defaults to 465)
        server_port: 465
        username: ${{ SECRETS.EMAIL_ACCOUNT }}
        password: ${{ SECRETS.EMAIL_PASSWORD }}
        sender: Dhaya
        from: ${{ SECRETS.EMAIL_ACCOUNT }}
        to: dhayanandh@gmail.com
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
