name: Send mail
on: push
jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send mail
      if: ${{ always() }} 
      uses: devellany/send-mailer@v1.0.2
      with:
        server_address: smtp.google.com
        # Optional port (defaults to 465)
        server_port: 465
        username: ${{SECRETS_ACCOUNT}}
        password: ${{SECRETS_MAIL_PASSWORD}}
        sender: Dhaya
        from: ${{SECRETS_ACCOUNT}}
        to: dhayanandh@gmail.com
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
